### ISSUE TITLE
Admit to slight incorrectness of object diagram depictions?

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#135]
In the DifferentNames and MatchCdOd tasks, the descriptive text already admits that class diagrams are displayed simplified:

![image](https://user-images.githubusercontent.com/5853832/123156689-dc714f00-d469-11eb-9c58-a4cc1ee8d02b.png)

But actually, the object diagrams also have a display problem, namely that the underlines are missing everywhere in picture like this:
![image](https://user-images.githubusercontent.com/5853832/123156781-fd39a480-d469-11eb-938e-c23118f627d6.png)
And some text about this? (Or would it only add confusion instead of helping?)

**Comment by marcellussiegburg** [comment]
I think (at least for the exam) there is not much benefit on adding a message (and leads to longer instructions! Which might distract further in the already very long document?). There are no other OD tasks (where students have to draw ODs) and they do not have to decide for validity of ODs. (Or do you have something special in mind where students would answer wrong because of the depiction issues?)

**Comment by jvoigtlaender** [comment]
Probably this issue is obsolete? In so far as the missing underlines were only the case for the print-to-pdf-for-exam?

**Comment by marcellussiegburg** [comment]
Indeed.
