### ISSUE TITLE
Use record syntax/labels?

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#141]
In light of this definition:
https://github.com/jvoigtlaender/modelling-tasks-internal/blob/a8e12a052cd3f2c274838a86011367745449e623/src/Modelling/CdOd/Types.hs#L33 and uses like:
https://github.com/jvoigtlaender/modelling-tasks-internal/blob/a8e12a052cd3f2c274838a86011367745449e623/src/Modelling/CdOd/Types.hs#L94 it would probably be better to refactor this type (but also others, like `Od`, `Syntax` etc.) to introduce and allow the use of record labels.

Probably also making use of extensions like `NamedFieldPuns`.

Required steps:
- [X] introduce new `ClassDiagram` (and therefore required) datatype(s) and use it instead of `Syntax`
- [x] check completeness of new `ClassDiagram` and its associated datatypes
- [x] use `Relationship` instead of `Edge` in `src` ~and `test`~ Modules
- [x] move `Modelling.CdOd.Edges` to `legacy-app` and `test` Modules
- [x] introduce new `ObjectDiagram` datatype and use it instead of `Od`

*Edit: add required steps*
*Edit: slightly modify 3rd and 4th step*

**Comment by marcellussiegburg** [comment]
I introduced a new `ClassDiagram` datatype and made use for places where `Syntax` was used before.
@jvoigtlaender In the light of the second step above I would like to get feedback (i.e. if you think, there should something be changed.)

E.g. one could argue that `ClassDiagram`s fields should be named differently, like:
```Haskell
data ClassDiagram className relationshipName = ClassDiagram {
  classes       :: [className]
  relationships :: [Relationship className relationshipName]
  }
```
instead of
https://github.com/jvoigtlaender/modelling-tasks-internal/blob/65ddedfdf8979a64ee63cb33cf5139a97dc04282/src/Modelling/CdOd/Types.hs#L207-L210 (I avoided name clashes in the first place when creating this datatype, because fields of configuration options share this name at the moment)

Please let me know if you spot anything (before I continue with retiring the `Edge` datatype).

Another remark: The CD2Alloy transformation does not allow a class to inherit from multiple, different classes. I kept it that way. This was before visible via the datatype which the transformation expected this is now more hidden inside in places like:
https://github.com/jvoigtlaender/modelling-tasks-internal/blob/65ddedfdf8979a64ee63cb33cf5139a97dc04282/src/Modelling/CdOd/CD2Alloy/Transform.hs#L273

**Comment by jvoigtlaender** [comment]
I indeed also came to the conclusion that the `connections` field should rather be named `relationships`.

I also think that `connectTo` leads to confusing reading in a few places, e.g., when we have `connectTo from` and `connectTo to`. How about renaming `connectTo` into `linking`?

And maybe (though I am less sure about this) also `LimitedConnector` -> `LimitedLinking`? That would give
```haskell
data LimitedLinking nodeName = LimitedLinking {
  linking :: nodeName,
  limits  :: (Int, Maybe Int)
  }
```
which does make some sense.

**Comment by jvoigtlaender** [comment]
About the CD2Alloy transformation supporting only single inheritance, yes, I was aware of this as implemented. On paper, the transformation probably works also with multiple inheritance, and probably could have been implemented more generally. I just didn't bother at the time. Nevertheless, there could of course be some subtleties, so I wouldn't simply go for generalization now (as long as we don't need it).

And yes, I have (already had, before) an uneasy feeling about `listToMaybe` calls, since I guess we always use it with the expectation that it does not throw elements away, but that is not checked. Maybe, even if only to get explicit failures when violating the assumption in the future, all `listToMaybe` calls should be replaced by something like [`singleListToJust`](https://hackage.haskell.org/package/polysemy-plugin-0.4.4.0/docs/Polysemy-Plugin-Fundep-Utils.html#v:singleListToJust).

**Comment by marcellussiegburg** [comment]
I agree with everything. In order to resolve the conflict I propose changing:
https://github.com/jvoigtlaender/modelling-tasks-internal/blob/08189e9192bb29c68fb76cfa7f0a5d383f68fd7f/src/Modelling/CdOd/Types.hs#L285-L293 into
```Haskell
data ClassConfig = ClassConfig {
    classLimits       :: (Int, Int),
    aggregationLimits :: (Int, Maybe Int),
    associationLimits :: (Int, Maybe Int),
    compositionLimits :: (Int, Maybe Int),
    inheritanceLimits :: (Int, Maybe Int),
    -- | the number of relationships including inheritances
    relationshipLimits :: (Int, Maybe Int)
  } deriving (Eq, Generic, Read, Show)
```
(An alternative could be prefixing the old field names with config, i.e. `configClasses`, `...`)?

Later, I think, similar modifications should be applied to:
https://github.com/jvoigtlaender/modelling-tasks-internal/blob/08189e9192bb29c68fb76cfa7f0a5d383f68fd7f/src/Modelling/CdOd/Types.hs#L454-L461

**Comment by jvoigtlaender** [comment]
I like the version with `classLimits` etc.

**Comment by marcellussiegburg** [comment]
Removing `Edges` completely from `test`s seemed to be too much of an effort for not very much gain at the moment. This could maybe be done if test cases need amendment? (but not as part of this issue)

I drafted new datatypes for ODs which I like to discuss before applying all required changes to use them (as this has multiple consequences)
https://github.com/jvoigtlaender/modelling-tasks-internal/blob/d793042789e352f4cf5e6b9a17b638ba94f14708/src/Modelling/CdOd/Types.hs#L80-L85 https://github.com/jvoigtlaender/modelling-tasks-internal/blob/d793042789e352f4cf5e6b9a17b638ba94f14708/src/Modelling/CdOd/Types.hs#L102-L108 https://github.com/jvoigtlaender/modelling-tasks-internal/blob/d793042789e352f4cf5e6b9a17b638ba94f14708/src/Modelling/CdOd/Types.hs#L110-L115
The first datatype should avoid splitting at dollar signs like for instance `C$1` in multiple places. `C$1` would then become
```Haskell
Object { 
  objectName = "c1", 
  objectClass = "C" 
  } 
```
this would allow having custom object names (for custom instances), but at the same time prevent automatic renaming if the `objectName` does not start with a `c` in this case. Within the `ObjectDiagram` datatype the `objectName` is used for referencing, i.e. has to be unique across all objects. Both is no limitation considering the current naming conventions (but probably requires additional instance checks for custom instances). The `Object` datatype could later be extended with a field `isAnonymous :: Bool` for manual and automatic customisation of anonymous objects (instead of the current while-drawing-approach). The primes would be removed after the field names of `ObjectDiagram` (and exist at the moment only because of a conflict to `ObjectConfig` fields which would be renamed as mentioned in https://github.com/jvoigtlaender/modelling-tasks-internal/issues/141#issuecomment-1431172556).

@jvoigtlaender Do you have any objections or suggestions at this point?

**Comment by jvoigtlaender** [comment]
Sounds reasonable.
