### ISSUE TITLE
Anzeige/Formulierungen bei SelectValidCd-Direct

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#157]
![image](https://user-images.githubusercontent.com/5853832/140890763-5cf7b250-d4a8-4bd6-9743-5c72a46238f3.png)
![image](https://user-images.githubusercontent.com/5853832/140890829-4b3d4c6a-0991-4663-beb5-f82610613b09.png)

**Comment by marcellussiegburg** [comment]
Concerning the first image: Is this about removing the space before "würde"? Or should `[1, 2]` be indented (i.e. like "Yes." / "No." is in feedback)? I am not very opinionated about either. What would you prefer? (Both are a result of how Autotool treats translated text and require (in my opinion) a probably simple backend fix; I would prefer having "normal" text rather than typewriter style for non-code, but I am currently not able to achieve this (as this requires more advanced fixes in Autotools internals.))

**Comment by jvoigtlaender** [comment]
It is just the space that I found strange.
