### ISSUE TITLE
Resolve remaining issues of other AD repository

### ISSUE THREAD

**Issue by marcellussiegburg** [fmidue/modelling-tasks#182]
These remaining issues are:
- fmidue/ba-athena-schulz#21
- fmidue/ba-athena-schulz#15
- fmidue/ba-athena-schulz#12
- fmidue/ba-athena-schulz#11
- fmidue/ba-athena-schulz#10

**Comment by AthenaSchulz** [comment]
All remaining issues except the following should be done by now:

- fmidue/ba-athena-schulz#21 : No idea what could be done about this except adding ranges for stuff like `cycles` as mentioned previously, but that would require changes in the scope estimation as well (which is doable, but wouldnt it be more effort for someone trying to understand the code in the repo than to solve a very basic exercise? Plus without leaking additional information, this should only be an issue with a preset configuration used). But adding ranges might be desirable for configuration purposes anyway.

- https://github.com/fmidue/ba-athena-schulz/issues/12 : Basically the same left as https://github.com/fmidue/ba-athena-schulz/issues/11 as I can tell, `minAnswerLength` and `maxAnswerLength` options and checking after alloy generation is implemented by now. (Maybe there is a possiblity to handle this in Alloy, but that would probably require some work). The Activity End issue is at least partially fixed (by only allowing flow ends), but I could try to work on making Activity Ends work if needed urgently (otherwise maybe the issue could be moved here for long term?)

**Comment by marcellussiegburg** [comment]
> The Activity End issue is at least partially fixed (by only allowing flow ends), but I could try to work on making Activity Ends work if needed urgently (otherwise maybe the issue could be moved here for long term?)

@AthenaSchulz I suggest you create an issue (here) containing a description of what is covered and what is still missing for this, try to be as precise as possible (and probably using examples?).

**Comment by AthenaSchulz** [comment]
> > The Activity End issue is at least partially fixed (by only allowing flow ends), but I could try to work on making Activity Ends work if needed urgently (otherwise maybe the issue could be moved here for long term?)
> 
> @AthenaSchulz I suggest you create an issue (here) containing a description of what is covered and what is still missing for this, try to be as precise as possible (and probably using examples?).

Should be done with https://github.com/jvoigtlaender/modelling-tasks-internal/issues/187
