### ISSUE TITLE
Remove unnecessary seeds and use MonadRandom whenever possible

### ISSUE THREAD

**Issue by marcellussiegburg** [fmidue/modelling-tasks#184]
For instance shuffleADLabels takes an `Int` but should rather have a `MonadRandom m` context and return type `m (Map Int Int, UMLActivityDiagram)`
https://github.com/jvoigtlaender/modelling-tasks-internal/blob/40445a83b97dee0c89f95ea3a07ca6c60a2c2670/src/Modelling/ActivityDiagram/Shuffle.hs#L26-L32
Also `MonadRandom` should be used instead of similar parameters to `Int` like `StdGen` here
https://github.com/jvoigtlaender/modelling-tasks-internal/blob/40445a83b97dee0c89f95ea3a07ca6c60a2c2670/src/Modelling/ActivityDiagram/Auxiliary/Util.hs#L33-L42
And some data types define seeds without ever requiring them e.g.
https://github.com/jvoigtlaender/modelling-tasks-internal/blob/40445a83b97dee0c89f95ea3a07ca6c60a2c2670/src/Modelling/ActivityDiagram/MatchAD.hs#L60-L64 These superfluous fields should be removed completely

**Comment by AthenaSchulz** [comment]
1. For the shuffling functions `shuffleADLabels` , `shuffleADNames` and `shufflePetri` of Shuffle.hs, the `Int` parameter was replaced by a `MonadRandom` context
2. For `weightedShuffle` the `StdGen` parameter was replaced by a `MonadRandom` context as well, although it is still used with on a generator derived from a seed here (https://github.com/jvoigtlaender/modelling-tasks-internal/blob/06ed4b14d00be2874c03f6be8611ef56459a3829/src/Modelling/ActivityDiagram/SelectPetri.hs#L232) in order to not having to change the derivation of wrongNets (https://github.com/jvoigtlaender/modelling-tasks-internal/blob/06ed4b14d00be2874c03f6be8611ef56459a3829/src/Modelling/ActivityDiagram/SelectPetri.hs#L209).

(Im not completely sure how to rewrite that part nicely in order to add a `MonadRandom` context to `modifyAD` and `selectPetrinet` yet)

**Comment by marcellussiegburg** [comment]
I am uncertain if this is a call for help or just a notion that it will take a while. Is the requirement of laziness a "problem" here? Maybe using or implementing something along the lines of https://hackage.haskell.org/package/monad-extras-0.6.0/docs/Control-Monad-Extra.html#v:sequenceUntil would help?

**Comment by AthenaSchulz** [comment]
> I am uncertain if this is a call for help or just a notion that it will take a while. Is the requirement of laziness a "problem" here? Maybe using or implementing something along the lines of https://hackage.haskell.org/package/monad-extras-0.6.0/docs/Control-Monad-Extra.html#v:sequenceUntil would help?

More of a call for help, since Im not too experienced on working with Monads.
As of now, the mentioned code was replaced by a more "imperative" version using `loopM` (https://github.com/jvoigtlaender/modelling-tasks-internal/blob/0c23492ed9f42a73ae9d1ff789a7b7451676e972/src/Modelling/ActivityDiagram/SelectPetri.hs#L212), which should do what was previously done with lazy evaluation.

**Comment by AthenaSchulz** [comment]
In `src/Modelling/ActivityDiagram`:

- Every instance where an `Int` Seed or a `StdGen` was passed as a parameter was replaced by a `MonadRandom m` context
- Unneeded seeds in the instance datatypes were removed
