### ISSUE TITLE
Improve diversity of Alloy retrieved ODs for generated CDs?

### ISSUE THREAD

**Issue by marcellussiegburg** [fmidue/modelling-tasks#196]
Originating from this change and related discussion
https://github.com/jvoigtlaender/modelling-tasks-internal/commit/668a34b7e90ea00922a9074e7e858c7351833063#commitcomment-102035355

Earlier shuffling might improve the diversity of ODs for generated CDs. This is probably relevant to MatchCdOd and DifferentNames.

For more context I (essentially) copy the concluding part of the discussion:
[Because of omitting the shuffling via the commit above it] could be that less CD-OD-Combinations could be found (over multiple runs) for limited number of returned instances (or using timeout). Or more specific a lower range of ODs for the same amount of CDs [if order is indeed relevant to Alloy].

If we want to have a similar behaviour as before, I suggest reintroducing shuffling explicitly (between line 549 and 550; and if required also in other task types) rather than implicitly while retrieving the instance.

https://github.com/jvoigtlaender/modelling-tasks-internal/blob/668a34b7e90ea00922a9074e7e858c7351833063/src/Modelling/CdOd/MatchCdOd.hs#L549-L550

**Comment by jvoigtlaender** [comment]
Maybe just for the record (?):

The shuffling introduced in the above commits is not really the shuffling that this issue (or the referenced comment in the first message) was about, right?

There, the shuffling (which was removed) was affecting the names of entities in the CD. And the theory was that this (among other things) might have an impact on Alloy's SAT formula generation etc. That is, whether say the simplest class in a model is called `A` or `C` might have an impact (due to symmetry reduction, lexicographic ordering in generated formulas or whatnot) on what satisfying instances are generated or in what order.

The shuffling introduced now does not have this "renaming" effect.

(The previous shuffling did have, because it was shuffling names obtained from an Alloy instance and *then* zipping those name lists with `['A' ..]` and `['z', 'y' ..]` before further use.)

**Comment by marcellussiegburg** [comment]
Yes, it is not the original shuffling that was meant in the comment. This shuffling is just changing the order of elements (which is influencing Alloy as well).

This change was a very low-hanging fruit. Maybe it is worth to (also) do the name shuffling.
