### ISSUE TITLE
Rule out ambiguous mappings for MatchPetri

### ISSUE THREAD

**Issue by marcellussiegburg** [fmidue/modelling-tasks#198]
Currently it is possible to get following instance:
![activitydiagram](https://github.com/jvoigtlaender/modelling-tasks-internal/assets/531939/0fbacfd4-de2c-4e17-9de5-517477bafd07) ![petrinet](https://github.com/jvoigtlaender/modelling-tasks-internal/assets/531939/e1b149c4-389e-47ab-8a98-ee88e6c560ba)
The task deems this as correct solution
```haskell
MatchPetriSolution 
  { actionNodes = [ ( "E", 11 ), ( "A", 13 ), ( "D", 21 ), ( "F", 15 ) ]
  , objectNodes = [ ( "G", 24 ), ( "B", 19 ), ( "H", 16 ), ( "C", 12 ) ]
  , decisionNodes = [ 18, 8 ]
  , mergeNodes = [ 14, 4 ]
  , forkNodes = [ 17 ]
  , joinNodes = [ 2 ]
  , initialNodes = [ 25 ]
  , supportSTs = [ 3, 10, 1, 23, 9, 20, 5, 6, 7 ] 
  }
```
But this would be correct as well:
```haskell
MatchPetriSolution 
  { actionNodes = [ ( "E", 11 ), ( "A", 13 ), ( "D", 21 ), ( "F", 15 ) ]
  , objectNodes = [ ( "G", 24 ), ( "B", 19 ), ( "C", 16 ), ( "H", 12 ) ]
  , decisionNodes = [ 18, 8 ]
  , mergeNodes = [ 14, 4 ]
  , forkNodes = [ 17 ]
  , joinNodes = [ 2 ]
  , initialNodes = [ 25 ]
  , supportSTs = [ 3, 10, 1, 23, 9, 20, 5, 6, 7 ] 
  }
```
(I.e switching `C` and `H`)

Proposal implement a check which rules out any renamings (besides identity) resulting in an isomorph Petri net. Use this check for a generate and test approach.

**Comment by marcellussiegburg** [comment]
It seems that the latter check is not exactly what is helping here. It would rule out this example of course. But (too) many more as well. Consider the above example. Applying the renaming witch switches only the two transitions `20` and `15` (`[20->15, 15->20, id]`) would result in an isomorph Petri net which would not be ambiguous if `4`, `12` and `7` would not exist.

**Comment by jvoigtlaender** [comment]
I'm not sure I understand the problem.

Maybe the issue is what is meant by "isomorphic".

The check in my opinion should be: After renaming, do the original and renamed Petri net hav exactly the same mathematical representation (say, in the mathematical notation from the lecture).

In the Petri net from the first comment in this issue here, the following holds:
1. Write down the mathematical notation from the lecture.
2. Now apply the following renamings: 20 <-> 5, 16 <-> 12, 6 <-> 7.
3. Then write down the mathematical notation from the lecture for the renamed Petri net.
4. It turns out that the equations written down in 1. are exactly the same equations as those written down in 3.

I don't see how the same is true (or can be made true) with a renaming 20 <-> 15.

**Comment by jvoigtlaender** [comment]
And another way to phrase this is: Give me all isomorphisms of the Petri net to itself. There should only be one.

For the original Petri net above, there are exactly two auto-isomorphisms:
- id
- 20 <-> 5, 16 <-> 12, 6 <-> 7, id for all other nodes

I don't think there is an auto-isomorphism with 20 <-> 15 (also not after deleting a few nodes).

**Comment by jvoigtlaender** [comment]
A refined approach should be possible:
1. Given the Petri net, compute all permutations that make an auto-isomorphism.
2. For each permutation, apply it to the `MatchPetriSolution` structure and check whether the renamed `MatchPetriSolution` is equivalent to the original one (where order in the lists is irrelevant for this equivalence check).
3. If only the identity permutation survives this check, then the AD/Petri net pair is okay. Otherwise it cannot be used.

**Comment by marcellussiegburg** [comment]
The `hgal` library provides in fact a  [`automorphisms` function](https://hackage.haskell.org/package/hgal-2.0.0.3/docs/Data-Graph-Automorphism.html#v:automorphisms) which can be used (as we already are able to transform a petrinet into the required `Graph` type) and simplifies things again. It returns 3 permutations in the above case (of which one is a duplicate; but applying `nubOrd` is a trivial amendment to rule out duplicates). Runtime is 24 seconds on my machine for the above example (in ghci) and thus acceptable.

**Comment by jvoigtlaender** [comment]
After some reflection, I'm not sure if the "refined approach" from above is worth it, or even harmful. Maybe it's best to simply require that only the identity automorphism exists (i.e., that after `nubOrd`) only one automorphism exists.

The reasoning for this is as follows:

If some non-identity automorphism exists that survives the "on the `MatchPetriSolution` structure it gives an equivalent result" check, then that could for example mean that for two decision nodes the order/identity is open/ambiguous. That is, in the AD exist two decision nodes and it is both correct to match the first one to Petri net node 18, and the second one to Petri net node 8, or to indeed match the first one to 8 and the second one to 18. While that would indeed mean that the answer the student gives can be uniquely checked (despite there being some ambiguity in the translation), it could also mean that this student got a more complicated task instance than another student where such a choice did not exist. That is, for the other student all matching was "deterministic", whereas the current student maybe had some "choice point" and could in theory have had a hard time to convince themselves that it does not matter which choice they make.
