### ISSUE TITLE
Introduce Clever Feedback for SelectValidCd Task

### ISSUE THREAD

**Issue by marcellussiegburg** [fmidue/modelling-tasks#199]
Feedback should refer to the given instance in order to help students finding the correct answer, especially in a non-graded exercise context. There are multiple options to realise this. This issue is about implementing any form of such intelligent feedback. Multiple different strategies might also be configurable within the task type.

Consider the following SelectValidCd task instance:
![image](https://github.com/jvoigtlaender/modelling-tasks-internal/assets/531939/436d9d7b-7fee-4e7e-8166-fdd523d2faeb)
The correct answer stating all valid class diagrams is `[1,4]`.

Consider the following submission: `[1,3]`.
Feedback could be:
Your answer would be correct if
1. would have `w` as additional composition that makes `E` a part of `B`s where `E` participates exactly once and `B` participates `0..1` times 
2. relationship `w` would have limits `1` at its part end
3. relationship `z` would have limits `1` at its whole end
4. relationship `v` would have limits `*..1` at its whole end

There are several options (each could be configurable or always be the same):
1. Feedback could reference only class diagrams which were chosen wrongly (i.e. feedback on 1 and 2 would be droped in the example above; 1 and 2 are in fact distractors in the example above) or all class diagrams.
2. Feedback could only adhere to settings configured in the task (this is the case above; class diagrams become wrong only by introducing wrong composition limits; alternatives could be: separately configurable or all possible modifications)
3. Feedback could provide changes only to critical parts (this is the case above; could require some effort on the Alloy part (or the introduction of some generate and filter/test method)).
4. Feedback could vary for multiple submissions: either by having a different set of feedback for each possible answer (would be the same for the same submission given twice) or by choosing randomly from a given set for each class diagram (could be different for the same submission on the second time).

@jvoigtlaender please let me know if you are opposed to or very fond of any specific suggestions

*edit: typos, move parenthesis for better understanding*

**Comment by jvoigtlaender** [comment]
First off, I don't understand the specific feedback above:

> Your answer would be correct if
> 1. would have `w` as additional composition that makes `E` a part of `B`s where `E` participates exactly once and `B` participates `0..1` times 
> 2. relationship `w` would have limits `1` at its part end
> 3. relationship `z` would have limits `1` at its whole end
> 4. relationship `v` would have limits `*..1` at its whole end

Does the 1. point apply to CD 1, the 2. point to CD 2, etc.? But CD 1 is claimed to be correct, and also the student entered CD 1 as a correct one, so why does one have to say it "would be correct if ..."?

I think it only confuses to say anything on:
- CDs that are valid and were entered by the student as valid
- CDs that are invalid and were indicated (via not listing them) by the student as invalid

Of course, feedback should be given on:
- CDs the student claimed to be valid, but which actually are not valid; Then, the reason(s) can be given for why the CD is actually not valid.

I'm not sure about feedback on:
- CDs the student claimed to be invalud, but which actually are valid; Since we can't know why the student thought the CD is invalid, it is unclear how to correct that misconception via feedback, other than by saying "It actually is valid."

**Comment by jvoigtlaender** [comment]
In this case:
> - CDs the student claimed to be valid, but which actually are not valid; Then, the reason(s) can be given for why the CD is actually not valid.

I think it makes the most sense (at least initially, until we gain more experience with specific instances maybe) to provide one reason for why the CD is actually not valid. And if, for example, the task was configured to introduce multiplicity errors, then indeed the "chosen" reason to display for invalidity should probably be the relevant multiplicity error.

Does this address all open questions from the original comment?

**Comment by marcellussiegburg** [comment]
> Does the 1. point apply to CD 1, the 2. point to CD 2, etc.?

Yes, that was the idea.
> But CD 1 is claimed to be correct, and also the student entered CD 1 as a correct one, so why does one have to say it "would be correct if ..."?

That would not be required. Therefore I called it (and the second one) distractors and I guess you are right by:
> I think it only confuses to say anything on:
> - CDs that are valid and were entered by the student as valid
> - CDs that are invalid and were indicated (via not listing them) by the student as invalid

I think this could make sense if the feedback is used for learning with one task instance (by getting in fact different variations by giving different answers). But it could also be destructive if the intention is not clear enough.

I totally agree with your conclusions.

> I'm not sure about feedback on:
> - CDs the student claimed to be invalud, but which actually are valid; Since we can't know why the student thought the CD is invalid, it is unclear how to correct that misconception via feedback, other than by saying "It actually is valid."

I think there is no clear "help" available in this case. An option could be to provide a (or many) reduced version(s) of the class diagram by stripping one edge and telling. This simpler class diagram(s) is (or are) valid. Adding the stripped edge(s) does not make it (or them) invalid. An alternative could be listing all critical (by Alloy) checked properties, like:
- the class diagram does not have invalid limits
- the class diagram has no inheritance cycles
- ...

therefore it is valid.

> Does this address all open questions from the original comment?

Yes, thank you very much.

**Comment by marcellussiegburg** [comment]
In this case:
> - CDs the student claimed to be invalud, but which actually are valid; Since we can't know why the student thought the CD is invalid, it is unclear how to correct that misconception via feedback, other than by saying "It actually is valid."

We could present one OD, which is fitting to the presented CD. Stating something like:
The CD is in fact valid. Consider this OD, which is an instance of the given CD.

This might of course not be very helpful at all (as it is not clear why the student thougt it would be invalid in the first place), but it might provide a new perspective on the CD anyway.

**Comment by jvoigtlaender** [comment]
Yes, good idea. 

This specific feedback would need to be controlled by a configuration option, because there might be moments in the course where students do already know about CDs but not yet about ODs. 

Also, we should reflect on how much water this „semi-criterion: a CD is valid if an OD exists (or a negative version of this connection)“ carries for each of the specific ways by which we make non-valid CDs in this task type. (To at least be aware of whether misconceptions could arise like „Oh, the syntactic constraints on a CD candidate are not so important as long as one can make an OD from it.“)

**Comment by jvoigtlaender** [comment]
Anf the OD that is displayed should be somewhat „interesting“. For example, it should probably make each class from the CD inhabited (even if simpler ODs populating only some of the classes also exist).

And maybe there should be explicit size/structural configurable constraints on the „evidence ODs“ as well?

**Comment by marcellussiegburg** [comment]
Yes, I guess, the proposed evidence tuning would be helpful.
At the moment an OD is created (but thrown away) as last check to figure out if the CD can safely be determined as valid by a student. (In the light of: if a CD has no instance, it does not make any sense, thus could be interpreted as invalid.) I would replace this check in favour of the configurable procedure, thus making the configuration mandatory even if presenting ODs would be disabled.

This here might require some exploring:
> For example, it should probably make each class from the CD inhabited (even if simpler ODs populating only some of the classes also exist).

Enforcing to tight constraints might make specific class diagram constallations unavailable for ever beeing presented. Maybe (clever) configuration parameters could help. Or using some incremental approach (check if an instance without inhabitation rules exists, then increasingly set some inhabitation rules and check for instances until no instance exists).

**Comment by jvoigtlaender** [comment]
> I would replace this check in favour of the configurable procedure, thus making the configuration mandatory even if presenting ODs would be disabled.

Makes sense.

About this: 

> might make specific class diagram constallations unavailable for ever beeing presented

Maybe indeed the condition "all classes can be inhabited at the same time" should be the only one that is enforced (no additional size constraints etc). I am now wondering whether right now we do actually present CDs for which it is not possible to inhabit all classes. If so, that might in itself be considered problematic, for the same reasons as "if a CD has no instance, it does not make any sense, thus could be interpreted as invalid". Let's say the CD has two classes A and B that are somehow prevented from being instantiated, but there is also a class C that can be instantiated. Do we want to show such a CD? If the argument against showing a CD with no instances at all is "students could think such a CD is not-valid because it is so strange it doesn't even have instances", then one could also make the argument "if a CD contains classes A, B, C, but only has instances that exclusively consist of C objects, then this means that the A-and-B-part of the CD is wrong or at least contradictory, and as such the whole CD is dubious, so is better 'rejected', i.e., considered invalid by some students".

**Comment by jvoigtlaender** [comment]
(About the incremental approach: Let's try to first do only low-hanging fruits, nothing requiring much additional engineering work here.)

**Comment by jvoigtlaender** [comment]
Concerning the "all classes can be inhabited at the same time" criterion for getting reasonable object diagrams (here, for feedback, and possibly elsewhere): Maybe we can even additionally require that also each association/aggregation/composition from the CD must appear at least once in the OD?

**Comment by marcellussiegburg** [comment]
I agree and think that it makes sense to provide an option for appearance of each relationship name and enforce it here.
