### ISSUE TITLE
Abstract over "capabilities"

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#242]
I now think that the strategy mentioned in https://github.com/jvoigtlaender/modelling-tasks-internal/issues/152#issuecomment-1954532658 might be quite nice.

The idea would be that here in this repo there is a module somewhat like the following:
```haskell
module Capabilities.Alloy

class Monad m => MonadAlloy m where
  getInstancesWith :: CallAlloyConfig -> String -> m [AlloyInstance]

instance MonadAlloy IO where
  getInstancesWith = Language.Alloy.Call.getInstancesWith
```
and similar modules `Capabilities.PlantUML` and `Capabilities.Graphviz` introducing classes `MonadPlantUML` and `MonadGraphviz` along with the corresponding `IO` instances. (And the same for any further external tools that might be in use somewhere.)

Functions like `nameCdErrorGenerate` then get types like `(MonadFail m, MonadAlloy m, MonadGraphviz m) => NameCdErrorConfig -> Int -> Int -> m NameCdErrorInstance`, manifesting (and statically ensuring) that they don't use runaway randomness, and additionally rather nicely documenting what external tools they use (and don't use - for example, that PlantUML is not used in the `Cd` tasks).

At the other end of the integration, over at Autotool, not much needs to be changed. The function `nameCdErrorGenerate` still can be used just as it is used now, as long as the relevant Autotool module over there has `import Capabilities.Alloy ()` and `import Capabilities.Graphviz ()`, which again happens to provide useful documentation about what external tools a task relies on.

**Comment by marcellussiegburg** [comment]
[Commits 781ad4d, ae91ad1, 56d39a1 contribute to this issue (but forgot to mention it)]

**Comment by marcellussiegburg** [comment]
Most of the modules can now use the mechanism which were provided by the latest commits, but there remains one unresolved "problem" and that is debugging.
First I was tempted to create a `Capabilities.Debug` module. But then I realised that it kind of contradicts the communication of the proposed contracts introduced by this issue. When allowing some arbitrary IO-Actions.
But I think it is time for a clean-up anyway and to strip all debugging variables, including the corresponding debugging code. I rarely use the mechanism anyway, and if I require debugging I add statements which do not end up in commits. I think the latter should be the preferred way of doing so in the future. Even better now, it is required to add a constraint like `MonadIO m` in order to be able to perform debugging. Furthermore (in the long run) if it would accidentally be contributed to the repository a (to be written) checker will reject this abuse. Hopefully this reduces code artefacts. If it should become necessary to persist debugging code later (again) I see two ways: introduce CPP flags (for explicit compiling with debugging enabled) or create a `Capabilities.Debug` module containing complex debugging functions (a combination of both is as well possible).
