### ISSUE TITLE
Optimization/expressiveness of Alloy code surrounding CD changes?

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#253]
I stumbled upon this:

Constraints about mutations are expressed negatively, in some sense (sometimes) rather indirectly. Specifically, when this is set: https://github.com/jvoigtlaender/modelling-tasks-internal/blob/615a8869f6c0e366d76a9ff377095557c66767de/src/Modelling/CdOd/CdAndChanges/Transform.hs#L135-L137 the Alloy code emitted will be all that's in here: https://github.com/jvoigtlaender/modelling-tasks-internal/blob/615a8869f6c0e366d76a9ff377095557c66767de/src/Modelling/CdOd/CdAndChanges/Transform.hs#L269-L288

One might as well have expected to instead emit something like this:
```alloy
        fact OnlyRemoves {
          all c : Change | no c.add and one c.remove
        }
```

Now I was asking myself two things:
1. Might there be an efficiency difference? That is, by telling Alloy explicitly what changes there will be, instead of letting it deduce from all the negatively stated properties including inlining all `changedKind` etc. helper predicates, what only is left.
2. Might there be a risk here in that we actually have to be sure that it even holds that all the negative properties together indeed leave exactly the desired thing left? So, do these expressions cover exactly all situations that could in theory exist in the model?

I'm not saying that as currently stated it is unsound (focusing on the second point). I haven't thought about it further. Most likely, everything is okay. But the fact alone that this has to be pondered, is maybe a warning sign. It could also arise as a question if anyone is ever looking at the Alloy code.

It's not really specific to the special case of "exactly Removes are allowed", though that's probably the prominent case arising from the current code.

**Comment by marcellussiegburg** [comment]
Let me drop some first thoughts on this:

The motivation of the negative emission of properties is, that they can be combined in order to achieve disabling different properties. I.e. we would not be able to just add `OnlyRemoves` and `OnlyAdds` in order to enable both. (Of course, defining tailored facts for each combination would be possible.)

Now I briefly put some thoughts on the mentioned points:
1. I assume there is a difference. When I removed the older predicate: https://github.com/jvoigtlaender/modelling-tasks-internal/blob/34a9dfbff7f831d3cc46679e767ad9def2e86827/src/Modelling/CdOd/CdAndChanges/Transform.hs#L121-L125 I had both predicates in place, the negative and this one. I compared runtimes of the relevant test case and noticed, that using both, the test case was running faster. I decided nevertheless to remove the redundancy.

   The problem with such performance tests is, that it is just some specific benchmark. We won't know if it just performs better in the testet cases. I.e. it might perform better when retrieving just a single instance, when retrieving significant more instances, when retrieving all instances or when there is no instance. Additionally other constraints might influence the performance result. Maybe there is some correlation, but maybe not. So the question would be: How would we know which version is performing better?
2. This is a reasonable concern. All possible combinations result from this predicate: https://github.com/jvoigtlaender/modelling-tasks-internal/blob/23aea252f48f12e15e5fd82c0f80561112916cb8/alloy/cd/generate.als#L140-L148 If there is a change made on the predicate it results in required changes on the other predicates (or perturbs soundness). A possible solution might be to rewrite this predicate (to be generated by Haskell) and enable specific lines depending on the enabled properties (there is no need to introduce separate lines, but maybe it is a good idea anyway for clarity):
   ```Haskell
   pred change [c : Change, rs : set Relationship] { 
     false
       or one c.add + no c.remove
       or one c.remove + no c.add
       or one c.remove and one c.add 
     no c.add or not c.add in rs 
     c.remove in rs 
     let c1 = changedLimit [c], 
         c2 = changedKind [c], 
         c3 = flip [c] | 
       one c.add and one c.remove iff false
         or c1
         or c2
         or c3 
   } 
   ```
   Enabled mutations could then be steered by enabling/disabling corresponding `or` lines.
